### ISSUE TITLE
Настроить SonarQube для проверки проекта на качество

### ISSUE THREAD

**Issue by rmuhamedgaliev** [genrihovna/library#9]
Для начала давай настроим локальный сонар что бы познакомится с [возможностями](https://docs.sonarqube.org/latest/). Для этого давай развернем его локально. 

Для этого создай в папке **docs** директорию **sonar**, а там файл docker-compose.yml со следующим содержимым:

```yml
version: "3"

services:
  sonarqube:
    image: sonarqube:9-community
    container_name: sonarqube
    restart: always
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=root
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - 9000:9000
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
```

Затем необходимо запустить этот файл при помощи команды `docker-compose up`, а далее перейти в браузере на [http://localhost:9000](http://localhost:9000).

Для того, что бы запустить проверку, необходимо добавить Maven плагин

```xml
  <plugin>
      <groupId>org.sonarsource.scanner.maven</groupId>
      <artifactId>sonar-maven-plugin</artifactId>
      <version>3.9.0.2155</version>
  </plugin>
```

Для конфигурации сканирования из Maven, создай файл [settings.xml](https://maven.apache.org/settings.html) и добавь следующее содержимое

```xml
<settings>
    <pluginGroups>
        <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
    </pluginGroups>
    <profiles>
        <profile>
            <id>sonar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <sonar.host.url>http://localhost:9000</sonar.host.url>
                <sonar.projectKey>{НАЗВАНИЕ_ПРОЕКТА}</sonar.projectKey>
                <sonar.login>{ТОКЕН АВТОРИЗАЦИИ}</sonar.login>
            </properties>
        </profile>
    </profiles>
</settings>
```

Детально можно почитать в [документации](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-maven/).

Затем необходимо самостоятельно настроить сканирование проекта в [SonarCloud](https://sonarcloud.io).
